version: '3'

services:
  app:
    build: .
    depends_on:
      - mysql-dev
    ports:
      - "80:8080"
  mysql-dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: King1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: tennis
    ports:
      - "3306:3306"
    volumes:
      - /jenkins/workspace/final/mysql-dump:/docker-entrypoint-initdb.d/:ro
