logging:
  level:
    org.springframework: WARN
    com.upog: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: tennisApp.log

spring:
 application:
  name: tennis 
  
# ===============================
# = JPA configurations
# ===============================
 jpa:
  database-platform: org.hibernate.dialect.Oracle10gDialect
  show-sql: true
  #properties:
   #hibernate:
    #dialect: org.hibernate.dialect.MySQL8Dialect
 jackson:
  serialization:
   fail-on-empty-beans: false
  
# ===============================
# = Hibernate datasource
# ===============================
 datasource:
   url: jdbc:mysql://tennis.cnx63aff1prh.us-east-1.rds.amazonaws.com:3306/tennis
   username: admin
   password: tennis123
   name: DBTENNIS 
   driver-class-name: com.mysql.jdbc.Driver
  

   
#jasypt:  
 # encryptor:
  # password: dev

#Need to be checked  
server:  
 #servlet:
  #context-path: /tennis    
---
spring:
 profiles: dev
server:
 port: 8080

---

spring:
 profiles: uat
server:
 port: 7071
