spring:
 application:
  name: reports
  
# ===============================
# = JPA configurations
# ===============================
 jpa:
  database-platform: org.hibernate.dialect.Oracle10gDialect
  show-sql: true
  
# ===============================
# = Hibernate datasource
# ===============================
 datasources:
  datasource-1:  
   jdbc-url: jdbc:oracle:thin:@oraasswd14-scan.nam.nsroot.net:8889/CSANA1D
   username: CADENT
   password: Madrid92
   driver-class-name: oracle.jdbc.OracleDriver 
   name: ANALYZER 
  
  datasource-2:  
   jdbc-url: jdbc:oracle:thin:@oraasgtd34-scan.nam.nsroot.net:8889/CSFIN1D
   username: CSFIN_RCM_EXT
   password: Puding10
   driver-class-name: oracle.jdbc.OracleDriver
   name: CITISEARCH 
   
#jasypt:  
 # encryptor:
  # password: dev

#Need to be checked  
server:  
 servlet:
  context-path: /reports    
---
spring:
 profiles: dev
server:
 port: 9090
 address: 10.108.144.30
---

spring:
 profiles: uat
server:
 port: 7071
